# Generated by Django 3.2.23 on 2024-01-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(choices=[('sala1', '3'), ('sala2', '2')], max_length=100)),
                ('dolazak', models.TimeField()),
                ('odlazak', models.TimeField()),
                ('datum', models.DateField()),
                ('razlog', models.TextField()),
                ('napomena', models.TextField()),
                ('ime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
