# Generated by Django 3.2.23 on 2024-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sala',
            field=models.CharField(choices=[('sala1', '305'), ('sala2', '209')], max_length=100),
        ),
    ]
