# Generated by Django 3.2.23 on 2024-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_post_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sala',
            field=models.CharField(choices=[('sala1', 'sala1'), ('sala2', 'sala2'), ('sala3', 'sala3'), ('sala4', 'sala4'), ('sala5', 'sala5'), ('sala6', 'sala6'), ('sala7', 'sala7')], max_length=100),
        ),
    ]
